config/routes.rb
Rails.application.routes.draw do
  resources :entries
  get 'home/index'
  root 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all.order(:id).reverse
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body, :tag)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry, :html => { :class => "form-horizontal entry" } do |f| %>

  <% if @entry.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :body, :class => 'form-control' %>
    </div>
    <%=f.error_span(:body) %>
  </div>
  <div class="form-group">
    <%= f.label :tag, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tag, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tag) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                entries_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/entries/edit.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entries/index.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1>投稿一覧</h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:tag) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.id, entry_path(entry) %></td>
        <td><%= entry.title %></td>
        <td>
          <a role="button" data-toggle="collapse" href="#collapseBody<%=entry.id.to_s%>" aria-expanded="false" aria-controls="collapseBody<%=entry.id.to_s%>">
            <%= entry.body[0..10] %><% if entry.body.length > 15 %>...<% end %>
          </a>
        </td>
        <td><%= entry.tag %></td>
        <td><%= entry.updated_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
        <td>
          <%= link_to t('.show', :default => "詳細"),
            entry_path(entry), :class => 'btn btn-default' %>
          <%= link_to t('.edit', :default => "編集"),
            edit_entry_path(entry), :class => 'btn btn-info' %>
          <%= link_to t('.destroy', :default => "削除"),
            entry_path(entry),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>
        </td>
      </tr>
      <tr style="height:0px">
        <td colspan="6">
          <div class="collapse" id="collapseBody<%=entry.id.to_s%>">
            <div class="well"><%= simple_format(entry.body) %></div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_entry_path,
            :class => 'btn btn-primary' %>

app/views/entries/new.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entries/show.html.erb
<%- model_class = Entry -%>
<div class="page-header">
  <h1><%= @entry.title %></h1>
  <%= @entry.tag%>
</div>

<div class="row">
  <div class="col-md-12">
    <%= simple_format(@entry.body) %>
  </div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              entries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_entry_path(@entry), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              entry_path(@entry),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
<p>Find me in app/views/home/index.html.erb</p>

<form action="https://pt01.mul-pay.jp/link/tshop00023288/Multi/Entry" method="post">
  <input type="hidden" name="ShopID" value="tshop00023288"/>
  <input type="hidden" name="OrderID" value="order002"/>
  <input type="hidden" name="Amount" value="5000"/>
  <input type="hidden" name="Tax" value="400"/>
  <input type="hidden" name="DateTime" value="20160602180000"/>
  <input type="hidden" name="ShopPassString" value="5bc43007ca9ebe80b25e0e095564dce9"/>
  <input type="hidden" name="RetURL" value="http://localhost:8888/moodle/enrol/index.php?id=2"/>
  <input type="hidden" name="UseCvs" value="1"/>
  <input type="hidden" name="ReceiptsDisp11" value="大阪市北区梅田"/>
  <input type="hidden" name="ReceiptsDisp12" value="0612345678"/>
  <input type="hidden" name="ReceiptsDisp13" value="10:00-17:00"/>
  <input type="submit" value="Buy now">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qknote</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>